on: push
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['7.0.x']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: Build solution
      run: dotnet build -c Release

    - name: Test solution and upload code coverage
      run: |
        chmod +x test.sh
        ./test.sh
